# Generated by Django 4.2.7 on 2023-11-08 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade_servico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('num_nota', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EtapaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhes', models.TextField()),
                ('atividade_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.atividadeservico')),
            ],
        ),
        migrations.CreateModel(
            name='ExecucaoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario_emitiu_ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('qtde_por_embalagem', models.IntegerField()),
                ('qtde_atual', models.IntegerField()),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.fabricante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.grupocategoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_registro', models.DateTimeField()),
                ('detalhamento', models.TextField()),
                ('nome_receita', models.ForeignKey(limit_choices_to={'tipo__nome_tipo': 'ProdutoAcabado'}, on_delete=django.db.models.deletion.CASCADE, to='industria.produto')),
            ],
        ),
        migrations.CreateModel(
            name='SaidaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('destinatario', models.CharField(max_length=100)),
                ('num_nota', models.CharField(max_length=100)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='SubgrupoSubcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subgrupo_subcategoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TesteQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste_qualidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_transacao', models.CharField(max_length=100)),
                ('tipo_entrada_ou_saida', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_unidade_medida', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TesteQualidadeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste_qualidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.testequalidade')),
            ],
        ),
        migrations.CreateModel(
            name='SaidaProdutoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.produto')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.saidaproduto')),
            ],
        ),
        migrations.AddField(
            model_name='saidaproduto',
            name='tipo_transacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.tipotransacao'),
        ),
        migrations.CreateModel(
            name='ReceitaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('nome_unidade_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='industria.unidademedida')),
                ('produto', models.ForeignKey(limit_choices_to={'tipo__nome_tipo': 'Ingrediente'}, on_delete=django.db.models.deletion.CASCADE, to='industria.produto')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.receita')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='subgrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.subgruposubcategoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.tipo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.unidademedida'),
        ),
        migrations.CreateModel(
            name='ProducaoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_termino', models.DateTimeField()),
                ('etapa_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.etapaproducao')),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.execucaoetapa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.funcionario')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.receita')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemProducaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.ordemproducao')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.receita')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemProducaoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_termino', models.DateTimeField()),
                ('funcionario_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.funcionario')),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.ordemproducao')),
            ],
        ),
        migrations.AddField(
            model_name='execucaoetapa',
            name='ordem_producao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.ordemproducao'),
        ),
        migrations.AddField(
            model_name='etapaproducao',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.receita'),
        ),
        migrations.CreateModel(
            name='EntradaProdutoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.entradaproduto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.produto')),
            ],
        ),
        migrations.AddField(
            model_name='entradaproduto',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.fabricante'),
        ),
        migrations.AddField(
            model_name='entradaproduto',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.funcionario'),
        ),
        migrations.AddField(
            model_name='entradaproduto',
            name='tipo_transacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.tipotransacao'),
        ),
    ]
