# Generated by Django 4.2.7 on 2023-11-30 10:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('predio', models.CharField(max_length=100)),
                ('qr_code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id_ronda', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_encerramento', models.DateTimeField(blank=True, null=True)),
                ('duracao_total', models.IntegerField(default=0, verbose_name='Duração (em segundos):')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id_ocorrencia', models.AutoField(primary_key=True, serialize=False)),
                ('local', models.CharField(max_length=100)),
                ('texto_ocorrencia', models.TextField()),
                ('horario', models.DateTimeField(default=django.utils.timezone.now)),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguranca.ronda')),
            ],
        ),
    ]
