# Generated by Django 4.2.7 on 2023-11-10 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
                ('objetivo', models.TextField(null=True)),
                ('owner', models.CharField(max_length=50, null=True, verbose_name='Criado_por')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(auto_now_add=True, null=True)),
                ('link', models.CharField(max_length=25, null=True)),
                ('link_resposta', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('text', 'text'), ('textarea', 'textarea'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('select', 'select')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name='Nome')),
                ('questionario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.questionario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.type')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, null=True)),
                ('questao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.questao')),
                ('questionario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.questionario')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name='Nome')),
                ('questao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.questao')),
            ],
        ),
    ]
