# Generated by Django 5.0.7 on 2024-08-07 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Galpao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Galpão',
                'verbose_name_plural': 'Galpões',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('galpao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sala', to='app.galpao', verbose_name='Galpão')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Baia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baia', to='app.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Baia',
                'verbose_name_plural': 'Baias',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do setor')),
                ('descricao', models.TextField(verbose_name='Descrição do setor')),
                ('usuarios', models.ManyToManyField(blank=True, related_name='setor', to=settings.AUTH_USER_MODEL, verbose_name='Usuários do setor')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('femea_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('macho_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data_hora_do_parto', models.DateTimeField(verbose_name='Data e hora do parto')),
                ('tipo', models.CharField(choices=[('Normal', 'Normal'), ('Cesárea', 'Cesárea')], max_length=255, verbose_name='Tipo de parto')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('femea_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='femea_partos', to='contenttypes.contenttype', verbose_name='Tipo de Fêmea')),
                ('macho_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macho_partos', to='contenttypes.contenttype', verbose_name='Tipo de Macho')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parto_setor', to='app.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Parto',
                'verbose_name_plural': 'Partos',
                'ordering': ['data_hora_do_parto'],
            },
        ),
        migrations.AddField(
            model_name='galpao',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galpao', to='app.setor', verbose_name='Setor'),
        ),
        migrations.CreateModel(
            name='Suino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao_unica', models.CharField(max_length=255, unique=True, verbose_name='Identificação única')),
                ('rfid', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='RFID')),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea'), ('Indefinido', 'Indefinido')], max_length=255, verbose_name='Sexo')),
                ('peso_de_nascimento', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Peso de nascimento')),
                ('data_hora_de_nascimento', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora de nascimento')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_especie', to='app.especie', verbose_name='Espécie')),
                ('mae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_mae', to='app.suino', verbose_name='Mãe')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_pai', to='app.suino', verbose_name='Pai')),
                ('raca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_raca', to='app.raca', verbose_name='Raça')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_setor', to='app.setor', verbose_name='Setor')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_tipo', to='app.tipo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Suíno',
                'verbose_name_plural': 'Suínos',
                'ordering': ['identificacao_unica'],
            },
        ),
    ]
