# Generated by Django 5.0.7 on 2024-08-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parto',
            name='femea_content_type',
        ),
        migrations.RemoveField(
            model_name='parto',
            name='femea_object_id',
        ),
        migrations.RemoveField(
            model_name='parto',
            name='macho_content_type',
        ),
        migrations.RemoveField(
            model_name='parto',
            name='macho_object_id',
        ),
        migrations.RemoveField(
            model_name='suino',
            name='data_hora_de_nascimento',
        ),
        migrations.RemoveField(
            model_name='suino',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='suino',
            name='id',
        ),
        migrations.RemoveField(
            model_name='suino',
            name='identificacao_unica',
        ),
        migrations.RemoveField(
            model_name='suino',
            name='mae',
        ),
        migrations.RemoveField(
            model_name='suino',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='suino',
            name='pai',
        ),
        migrations.RemoveField(
            model_name='suino',
            name='peso_de_nascimento',
        ),
        migrations.RemoveField(
            model_name='suino',
            name='raca',
        ),
        migrations.RemoveField(
            model_name='suino',
            name='rfid',
        ),
        migrations.RemoveField(
            model_name='suino',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='suino',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='suino',
            name='status',
        ),
        migrations.RemoveField(
            model_name='suino',
            name='tipo',
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao_unica', models.CharField(max_length=255, unique=True, verbose_name='Identificação única')),
                ('rfid', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='RFID')),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea'), ('Indefinido', 'Indefinido')], max_length=255, verbose_name='Sexo')),
                ('peso_de_nascimento', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Peso de nascimento')),
                ('data_hora_de_nascimento', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora de nascimento')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_especie', to='app.especie', verbose_name='Espécie')),
                ('mae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_mae', to='app.animal', verbose_name='Mãe')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_pai', to='app.animal', verbose_name='Pai')),
                ('parto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_parto', to='app.parto', verbose_name='Parto')),
                ('raca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_raca', to='app.raca', verbose_name='Raça')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_setor', to='app.setor', verbose_name='Setor')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_tipo', to='app.tipo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['identificacao_unica'],
            },
        ),
        migrations.AddField(
            model_name='parto',
            name='femea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='femea_parto', to='app.animal', verbose_name='Fêmea'),
        ),
        migrations.AddField(
            model_name='parto',
            name='macho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macho_parto', to='app.animal', verbose_name='Macho'),
        ),
        migrations.AddField(
            model_name='suino',
            name='animal_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.animal'),
            preserve_default=False,
        ),
    ]
