# Generated by Django 5.0.7 on 2024-08-12 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bovinocorte_bovinoleite_procedimento_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manejo',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manejo_lote', to='app.lote', verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='parto',
            name='quantidade_de_filhotes_mortos',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de filhotes mortos'),
        ),
        migrations.AddField(
            model_name='parto',
            name='quantidade_de_filhotes_mumificados',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de filhotes mumificados'),
        ),
        migrations.AddField(
            model_name='parto',
            name='quantidade_de_filhotes_vivos',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de filhotes vivos'),
        ),
    ]
