# Generated by Django 5.0.7 on 2024-08-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_manejo_lote_parto_quantidade_de_filhotes_mortos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do setor'),
        ),
    ]
