# Generated by Django 5.0.7 on 2024-08-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_setor_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bovinoleite',
            old_name='grau_sangue',
            new_name='grau_de_sangue',
        ),
    ]
