# Generated by Django 5.0.7 on 2024-08-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_grau_sangue_bovinoleite_grau_de_sangue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimentomanejo',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade'),
        ),
    ]
