# Generated by Django 4.2.6 on 2023-10-31 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('identificacao_unica', models.CharField(max_length=255, unique=True, verbose_name='Identificação Única')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, verbose_name='Sexo')),
                ('cor', models.CharField(max_length=255, verbose_name='Cor')),
                ('peso_nascimento', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Peso no nascimento')),
                ('data_hora_nascimento', models.DateTimeField(verbose_name='Data e hora do nascimento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='EspecieAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da espécie')),
            ],
            options={
                'verbose_name': 'Espécie do Animal',
                'verbose_name_plural': 'Espécies de Animal',
            },
        ),
        migrations.CreateModel(
            name='Fecundacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('femea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='femea_fecundacao', to='pecuaria.animal', verbose_name='Fêmea')),
            ],
            options={
                'verbose_name': 'Fecundação',
                'verbose_name_plural': 'Fecundações',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='InstrumentoCirurgico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Instrumento Cirúrgico',
                'verbose_name_plural': 'Instrumentos Cirúrgicos',
            },
        ),
        migrations.CreateModel(
            name='Manejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_manejo', models.DateTimeField(verbose_name='Data e hora do manejo')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.animal', verbose_name='Animal')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Manejo',
                'verbose_name_plural': 'Manejos',
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('fabricante', models.CharField(max_length=255, verbose_name='Fabricante')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='RacaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da raça')),
            ],
            options={
                'verbose_name': 'Raça do Animal',
                'verbose_name_plural': 'Raças de Animal',
            },
        ),
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do tipo')),
            ],
            options={
                'verbose_name': 'Tipo do Animal',
                'verbose_name_plural': 'Tipos de Animal',
            },
        ),
        migrations.CreateModel(
            name='TipoFecundacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo da Fecundação',
                'verbose_name_plural': 'Tipos de Fecundação',
            },
        ),
        migrations.CreateModel(
            name='TipoParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Parto',
                'verbose_name_plural': 'Tipos de Parto',
            },
        ),
        migrations.CreateModel(
            name='TipoProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo do Procedimento',
                'verbose_name_plural': 'Tipos de Procedimento',
            },
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo do Produto',
                'verbose_name_plural': 'Tipos de Produto',
            },
        ),
        migrations.CreateModel(
            name='TipoTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo da Transação',
                'verbose_name_plural': 'Tipos de Transação',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_transacao', models.DateTimeField(verbose_name='Data e hora da transação')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.animal', verbose_name='Animal')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.tipotransacao', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
        migrations.CreateModel(
            name='ProdutoManejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('manejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.manejo', verbose_name='Manejo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos utilizados no Manejo',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.tipoproduto', verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='ProcedimentoNoManejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('manejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.manejo', verbose_name='Manejo')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.procedimento', verbose_name='Procedimento')),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos utilizados no Manejo',
            },
        ),
        migrations.AddField(
            model_name='procedimento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.tipoprocedimento', verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='PartoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_parto', models.DateTimeField(verbose_name='Data e hora do parto')),
                ('quantidade_filhotes', models.PositiveIntegerField(verbose_name='Quantidade de filhotes')),
                ('matriz', models.ForeignKey(limit_choices_to={'sexo': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='matriz_parto', to='pecuaria.animal', verbose_name='Matriz')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.tipoparto', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Parto',
                'verbose_name_plural': 'Partos',
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaFecundacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_fecundacao', models.DateTimeField(verbose_name='Data e hora da fecundação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('fecundacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.fecundacao', verbose_name='Fecundação')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.tipofecundacao', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Ocorrência da fecundação',
                'verbose_name_plural': 'Ocorrências da fecundação',
            },
        ),
        migrations.AddField(
            model_name='fecundacao',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='fecundacao',
            name='macho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macho_fecundacao', to='pecuaria.animal', verbose_name='Macho'),
        ),
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.especieanimal', verbose_name='Espécie'),
        ),
        migrations.AddField(
            model_name='animal',
            name='matriz',
            field=models.ForeignKey(blank=True, limit_choices_to={'sexo': 'F'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriz_animal', to='pecuaria.animal', verbose_name='Matriz'),
        ),
        migrations.AddField(
            model_name='animal',
            name='pai',
            field=models.ForeignKey(blank=True, limit_choices_to={'sexo': 'M'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pai_animal', to='pecuaria.animal', verbose_name='Pai'),
        ),
        migrations.AddField(
            model_name='animal',
            name='parto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parto_animal', to='pecuaria.partoanimal', verbose_name='Parto'),
        ),
        migrations.AddField(
            model_name='animal',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.racaanimal', verbose_name='Raça'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.tipoanimal', verbose_name='Tipo'),
        ),
    ]
