# Generated by Django 4.2.7 on 2023-11-10 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pecuaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número do Lote')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='LoteAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Lote do Animal',
                'verbose_name_plural': 'Lote de Animais',
            },
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_parto', models.DateTimeField(verbose_name='Data e hora do parto')),
                ('tipo', models.CharField(choices=[('Normal', 'Normal (Assistido)')], default='Normal', max_length=255, verbose_name='Tipo')),
                ('numero_leitoes_vivos', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nº de leitões vivos')),
                ('numero_leitoes_mortos', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nº de leitões mortos')),
                ('numero_leitoes_mumificados', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nº de leitões mumificados')),
                ('quantidade_filhotes', models.PositiveIntegerField(verbose_name='Quantidade de filhotes')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Parto',
                'verbose_name_plural': 'Partos',
            },
        ),
        migrations.RenameModel(
            old_name='EspecieAnimal',
            new_name='Especie',
        ),
        migrations.RenameModel(
            old_name='ProcedimentoNoManejo',
            new_name='ProcedimentoManejo',
        ),
        migrations.RenameModel(
            old_name='RacaAnimal',
            new_name='Raca',
        ),
        migrations.RenameModel(
            old_name='TipoAnimal',
            new_name='Tipo',
        ),
        migrations.RemoveField(
            model_name='fecundacao',
            name='femea',
        ),
        migrations.RemoveField(
            model_name='fecundacao',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='fecundacao',
            name='macho',
        ),
        migrations.DeleteModel(
            name='InstrumentoCirurgico',
        ),
        migrations.RemoveField(
            model_name='ocorrenciafecundacao',
            name='fecundacao',
        ),
        migrations.RemoveField(
            model_name='ocorrenciafecundacao',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='partoanimal',
            name='matriz',
        ),
        migrations.RemoveField(
            model_name='partoanimal',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='pai',
        ),
        migrations.AddField(
            model_name='animal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='animal',
            name='reprodutor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__nome': 'Reprodutor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reprodutor_animal', to='pecuaria.animal', verbose_name='Reprodutor'),
        ),
        migrations.AddField(
            model_name='manejo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='manejo',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='cor',
            field=models.CharField(default='Rosa e Branco', max_length=255, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='matriz',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__nome': 'Matriz'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriz_animal', to='pecuaria.animal', verbose_name='Matriz'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='peso_nascimento',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Peso no nascimento (Kg)'),
        ),
        migrations.AlterField(
            model_name='manejo',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pecuaria.animal', verbose_name='Animal'),
        ),
        migrations.DeleteModel(
            name='Fecundacao',
        ),
        migrations.DeleteModel(
            name='OcorrenciaFecundacao',
        ),
        migrations.DeleteModel(
            name='TipoFecundacao',
        ),
        migrations.DeleteModel(
            name='TipoParto',
        ),
        migrations.DeleteModel(
            name='TipoTransacao',
        ),
        migrations.DeleteModel(
            name='Transacao',
        ),
        migrations.AddField(
            model_name='parto',
            name='matriz',
            field=models.ForeignKey(limit_choices_to={'tipo__nome': 'Matriz'}, on_delete=django.db.models.deletion.CASCADE, related_name='matriz_parto', to='pecuaria.animal', verbose_name='Matriz'),
        ),
        migrations.AddField(
            model_name='parto',
            name='reprodutor',
            field=models.ForeignKey(limit_choices_to={'tipo__nome': 'Reprodutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='reprodutor_parto', to='pecuaria.animal', verbose_name='Reprodutor'),
        ),
        migrations.AddField(
            model_name='loteanimal',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pecuaria.animal', verbose_name='Animal'),
        ),
        migrations.AddField(
            model_name='loteanimal',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pecuaria.lote', verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='manejo',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pecuaria.lote', verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='parto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parto_animal', to='pecuaria.parto', verbose_name='Parto'),
        ),
        migrations.DeleteModel(
            name='PartoAnimal',
        ),
    ]
