# Generated by Django 4.2.7 on 2023-11-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pecuaria', '0003_remove_animal_created_at_remove_manejo_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Setor')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.AlterModelOptions(
            name='loteanimal',
            options={'verbose_name': 'Lote do Animal', 'verbose_name_plural': 'Lotes de Animal'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pecuaria.tipo', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='numero',
            field=models.PositiveIntegerField(unique=True, verbose_name='Número do Lote'),
        ),
        migrations.AddField(
            model_name='animal',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pecuaria.setor', verbose_name='Setor'),
        ),
    ]
