# Generated by Django 4.2.7 on 2024-04-02 13:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pecuaria', '0004_setor_alter_loteanimal_options_alter_animal_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galpao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do galpão')),
            ],
            options={
                'verbose_name': 'Galpão',
                'verbose_name_plural': 'Galpões',
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da instituição')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.AlterModelOptions(
            name='especie',
            options={'verbose_name': 'Espécie', 'verbose_name_plural': 'Espécies'},
        ),
        migrations.AlterModelOptions(
            name='loteanimal',
            options={'verbose_name': 'Animal no lote', 'verbose_name_plural': 'Animais no lote'},
        ),
        migrations.AlterModelOptions(
            name='raca',
            options={'verbose_name': 'Raça', 'verbose_name_plural': 'Raças'},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'verbose_name': 'Tipo de animal', 'verbose_name_plural': 'Tipos de animais'},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='parto',
            name='quantidade_filhotes',
        ),
        migrations.AddField(
            model_name='animal',
            name='rfid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='RFID'),
        ),
        migrations.AddField(
            model_name='lote',
            name='numero_animais',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de animais'),
        ),
        migrations.AddField(
            model_name='parto',
            name='quantidade_total_leitoes',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade total de leitões'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='data_hora_nascimento',
            field=models.DateTimeField(verbose_name='Data e hora de nascimento'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pecuaria.especie', verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='identificacao_unica',
            field=models.CharField(max_length=255, unique=True, verbose_name='Identificação única'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='matriz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriz_animal', to='pecuaria.animal', verbose_name='Matriz'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='parto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pecuaria.parto', verbose_name='Parto'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='peso_nascimento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Peso de nascimento'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pecuaria.raca', verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='reprodutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reprodutor_animal', to='pecuaria.animal', verbose_name='Reprodutor'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=255, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='Número do lote'),
        ),
        migrations.AlterField(
            model_name='loteanimal',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pecuaria.animal', verbose_name='Animal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loteanimal',
            name='lote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pecuaria.lote', verbose_name='Lote'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manejo',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pecuaria.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='numero_leitoes_mortos',
            field=models.PositiveIntegerField(default=0, verbose_name='Nº de leitões mortos'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='numero_leitoes_mumificados',
            field=models.PositiveIntegerField(default=0, verbose_name='Nº de leitões mumificados'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='numero_leitoes_vivos',
            field=models.PositiveIntegerField(default=0, verbose_name='Nº de leitões vivos'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='tipo',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Cesárea', 'Cesárea')], default='Normal', max_length=255, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='procedimentomanejo',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='procedimentomanejo',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fabricante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='produtomanejo',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='produtomanejo',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do setor'),
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da unidade')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.instituicao', verbose_name='Instituição')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número da sala')),
                ('galpao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.galpao', verbose_name='Galpão')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_saida', models.DateTimeField(verbose_name='Data e hora da saída')),
                ('tipo', models.CharField(choices=[('Morte natural', 'Morte natural'), ('Abate sanitário', 'Abate sanitário'), ('Descarte', 'Descarte')], max_length=255, verbose_name='Tipo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
            },
        ),
        migrations.AddField(
            model_name='galpao',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.setor', verbose_name='Setor'),
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_cobertura', models.DateTimeField(verbose_name='Data e hora da cobertura')),
                ('data_repeticao_cio', models.DateField(blank=True, null=True, verbose_name='Data da repetição do cio')),
                ('data_prevista_parto', models.DateField(blank=True, null=True, verbose_name='Data prevista do parto')),
                ('matriz', models.ForeignKey(limit_choices_to={'tipo__nome': 'Matriz'}, on_delete=django.db.models.deletion.CASCADE, related_name='matriz_cobertura', to='pecuaria.animal', verbose_name='Matriz')),
                ('reprodutor', models.ForeignKey(limit_choices_to={'tipo__nome': 'Reprodutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='reprodutor_cobertura', to='pecuaria.animal', verbose_name='Reprodutor')),
            ],
            options={
                'verbose_name': 'Cobertura',
                'verbose_name_plural': 'Coberturas',
            },
        ),
        migrations.CreateModel(
            name='Baia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número da baia')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecuaria.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Baia',
                'verbose_name_plural': 'Baias',
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='baia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pecuaria.baia', verbose_name='Baia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setor',
            name='unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pecuaria.unidade', verbose_name='Unidade'),
            preserve_default=False,
        ),
    ]
