# Generated by Django 4.2.7 on 2023-11-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Área de Plantio',
                'verbose_name_plural': 'Áreas de Plantio',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cultivar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cultivar',
                'verbose_name_plural': 'Cultivares',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Fazenda',
                'verbose_name_plural': 'Fazendas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Ferramenta',
                'verbose_name_plural': 'Ferramentas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('nome_cientifico', models.CharField(max_length=50, verbose_name='Nome Científico')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoCultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Cultura',
                'verbose_name_plural': 'Tipos de Cultura',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoFerramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Ferramenta',
                'verbose_name_plural': 'Tipos de Ferramenta',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='VariedadePlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Variedade de Planta',
                'verbose_name_plural': 'Variedades de Planta',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Área')),
                ('medida', models.CharField(max_length=50, verbose_name='Medida')),
                ('areas_plantio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricola.areas', verbose_name='Área de Plantio')),
            ],
            options={
                'verbose_name': 'Talhão',
                'verbose_name_plural': 'Talhões',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Fim')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricola.ferramenta', verbose_name='Ferramenta')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_plantio', models.DateField(verbose_name='Data de Plantio')),
                ('data_colheita', models.DateField(verbose_name='Data de Colheita')),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('cultivar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricola.cultivar', verbose_name='Cultivar')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricola.planta', verbose_name='Planta')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricola.talhao', verbose_name='Talhão')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='planta',
            name='tipo_cultura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricola.tipocultura', verbose_name='Tipo de Cultura'),
        ),
        migrations.AddField(
            model_name='planta',
            name='variedade_planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricola.variedadeplanta', verbose_name='Variedade de Planta'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricola.tipoferramenta', verbose_name='Tipo'),
        ),
    ]
