# Generated by Django 4.2.7 on 2023-11-10 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('inauguration_date', models.DateField(verbose_name='Data de Inauguração')),
                ('latitude', models.CharField(max_length=50, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=50, verbose_name='Longitude')),
                ('number_of_slots', models.PositiveIntegerField(verbose_name='Número de Horários')),
            ],
            options={
                'verbose_name': 'Edifício',
                'verbose_name_plural': 'Edifícios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Corridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=45, unique=True, verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Corredor',
                'verbose_name_plural': 'Corredores',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=20, verbose_name='Nome do Dia')),
                ('order', models.PositiveIntegerField(verbose_name='Ordem do Dia')),
            ],
            options={
                'verbose_name': ' Dia da Semana',
                'verbose_name_plural': 'Dias da Semana',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='Nome')),
                ('room_count', models.IntegerField(verbose_name='Quantidade de Salas')),
                ('bathroom_count', models.IntegerField(verbose_name='Quantidade de Banheiros')),
            ],
            options={
                'verbose_name': 'Piso',
                'verbose_name_plural': 'Pisos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='Nome')),
                ('city', models.CharField(max_length=45, unique=True, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=55, verbose_name='Prédio')),
                ('number_rooms', models.CharField(max_length=55, verbose_name='Numero Sala')),
                ('data', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(verbose_name='Entrada')),
                ('end_time', models.TimeField(verbose_name='Saida')),
                ('name_allocation', models.CharField(max_length=100, verbose_name='Nome de quem irá alocar')),
                ('grade', models.CharField(max_length=100, verbose_name='Turma')),
                ('discipline', models.CharField(max_length=100, verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Alocação',
                'verbose_name_plural': 'Alocações',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, unique=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Status da Sala',
                'verbose_name_plural': 'Status das Salas',
                'ordering': ['status_name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Sala',
                'verbose_name_plural': 'Tipos de Sala',
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno'), ('Madrugada', 'Madrugada')], max_length=50, unique=True, verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['shift'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='Nome')),
                ('city', models.CharField(max_length=45, unique=True, verbose_name='Cidade')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.institution', verbose_name='Instituição')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['institution'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3, verbose_name='Número')),
                ('seats', models.IntegerField(verbose_name='Assentos')),
                ('color', models.CharField(default='bg-success', max_length=30, verbose_name='Cor')),
                ('can_be_reserved', models.BooleanField(default=True, verbose_name='Pode ser reservada')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.building', verbose_name='Prédio')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.roomtype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['building'],
            },
        ),
        migrations.CreateModel(
            name='ManageShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Hora de Início')),
                ('end_time', models.TimeField(verbose_name='Hora de Fim')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.shift', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Gerenciar Turno',
                'verbose_name_plural': 'Gerenciar Turnos',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='building',
            name='corridor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.corridor', verbose_name='Corredor'),
        ),
        migrations.AddField(
            model_name='building',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.floor', verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='building',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.institution', verbose_name='Instituição'),
        ),
        migrations.AddField(
            model_name='building',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.unit', verbose_name='Unidade'),
        ),
    ]
