# Generated by Django 4.2.7 on 2023-11-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallocation',
            name='end_time',
            field=models.TimeField(verbose_name='Saída'),
        ),
        migrations.AlterField(
            model_name='roomallocation',
            name='number_rooms',
            field=models.CharField(max_length=55, verbose_name='Número Sala'),
        ),
    ]
